sibur-activity-web/gettingstarted/urls.py
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

import hello.views

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    # path("", hello.views.index, name="index"),
    path('', include('hello.urls')),

    # path("predict", hello.views.predict, name="predict"),
    path("db/", hello.views.db, name="db"),
    path("admin/", admin.site.urls),
]

sibur-activity-web/hello/urls.py
from django.urls import include, path
from . import views
app_name = 'hello'
urlpatterns = [
    path('', views.index, name='index'), # ex: /about/
    path('atc_index', views.atc_index, name='atc_index'), # ex: /about/
    path('update/', views.update, name='update'), # ex: /about/
    path('atc_update/', views.atc_update, name='atc_update'), # ex: /about/
    path('uploadcsv/', views.uploadcsv, name='uploadcsv'), # ex: /about/
]

sibur-activity-web/hello/models.py
from django.db import models

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField("date created", auto_now_add=True)

sibur-activity-web/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Greeting
import requests
from django.conf import settings

import xlrd
import hello.mylib as mylib
import hello.mylib_feateng as mylib_feateng

from django.http import HttpResponseRedirect
import pdb #pdb.set_trace()
import pandas as pd

def uploadcsv(request): # pdb.set_trace();
    import pickle
    context = {'predictions': 'uploadcsv2','df': 'uploadcsv2','pred': 'uploadcsv2'}
    return render(request, "index.html", context)

def update(request):
    import pickle

    # activity
    filepath = settings.MEDIA_ROOT + '/products/'+ 'train_with_pred2' + '.csv'
    # filepath = settings.MEDIA_ROOT + '/products/'+ 'train_with_pred_backup' + '.csv'
    df = pd.read_csv(filepath, parse_dates=["date"], index_col="date").tail(460)#df = pd.read_json('NashDomRyazan-29-03-2019.json', encoding='utf-8')
    result = []
    result.append(['date', 'true', 'prediction'])
    for i in range(df.shape[0]):
        if df.iloc[i]['activity'] == 0: activity = 0
        else: activity = df.iloc[i]['activity']
        if df.iloc[i]['pred6h'] == 0: pred6h = 0
        else: pred6h = df.iloc[i]['pred6h']
        result.append([str(df.index[i]).split(' ')[1], activity, pred6h])

    # atactic
    # atc_filepath = settings.MEDIA_ROOT + '/products/'+ 'atc_pred' + '.csv'
    # atc_df = pd.read_csv(atc_filepath, parse_dates=["date"], index_col="date").tail(720)#df = pd.read_json('NashDomRyazan-29-03-2019.json', encoding='utf-8')
    # atc_result = []
    # # atc_result.append(['date', 'true1', 'true2', 'true3', 'prediction1', 'prediction2', 'prediction3'])
    # atc_result.append(['date', 'true1', 'prediction1'])
    # for i in range(atc_df.shape[0]):
    #     atc1 = df.iloc[i]['atactic_1']
    #     # atc2 = df.iloc[i]['atactic_2']
    #     # atc3 = df.iloc[i]['atactic_3']
    #     a1_pred6h = df.iloc[i]['a1_pred6h']
    #     # a2_pred6h = df.iloc[i]['a2_pred6h']
    #     # a3_pred6h = df.iloc[i]['a3_pred6h']
    #     # atc_result.append([str(df.index[i]), atc1, atc2, atc3, a1_pred6h, a2_pred6h, a3_pred6h])
    #     atc_result.append([str(df.index[i]), atc1, a1_pred6h])

    # # atactic fake
    # filepath = settings.MEDIA_ROOT + '/products/'+ 'train_with_pred2' + '.csv'
    # df = pd.read_csv(filepath, parse_dates=["date"], index_col="date").tail(720)#df = pd.read_json('NashDomRyazan-29-03-2019.json', encoding='utf-8')
    # atc_result = []
    # atc_result.append(['date', 'true', 'prediction'])
    # for i in range(df.shape[0]):
    #     if df.iloc[i]['activity'] == 0: activity = 0
    #     else: activity = df.iloc[i]['activity']
    #     if df.iloc[i]['pred6h'] == 0: pred6h = 0
    #     else: pred6h = df.iloc[i]['pred6h']
    #     atc_result.append([str(df.index[i]), activity, pred6h])
    values = [round(df.head(1)['f0'][-1],2), round(df.head(1)['f1'][-1],2), round(df.head(1)['f7'][-1],2), round(df.head(1)['f14'][-1],2), round(df.head(1)['f41'][-1],2), round(df.head(1)['f50'][-1],2)]
    import json
    # response = HttpResponse(json.dumps({'product_values_count': '123', 'prediction':result, 'atc_prediction':atc_result}))
    response = HttpResponse(json.dumps({'product_values_count': '123', 'prediction':result,'values':values}))
    return response

    # context = {'predictions': 'update','df': 'update','pred': 'update'}
    # return render(request, "index.html", context)

def atc_update(request):
    import pickle

    # atactic
    # atc_filepath = settings.MEDIA_ROOT + '/products/'+ 'atc_pred' + '.csv'
    # atc_df = pd.read_csv(atc_filepath, parse_dates=["date"], index_col="date").tail(720)#df = pd.read_json('NashDomRyazan-29-03-2019.json', encoding='utf-8')
    # atc_result = []
    # # atc_result.append(['date', 'true1', 'true2', 'true3', 'prediction1', 'prediction2', 'prediction3'])
    # atc_result.append(['date', 'true1', 'prediction1'])
    # for i in range(atc_df.shape[0]):
    #     atc1 = atc_df.iloc[i]['atactic_1']
    #     # atc2 = df.iloc[i]['atactic_2']
    #     # atc3 = df.iloc[i]['atactic_3']
    #     a1_pred6h = atc_df.iloc[i]['a1_pred6h']
    #     # a2_pred6h = df.iloc[i]['a2_pred6h']
    #     # a3_pred6h = df.iloc[i]['a3_pred6h']
    #     # atc_result.append([str(df.index[i]), atc1, atc2, atc3, a1_pred6h, a2_pred6h, a3_pred6h])
    #     atc_result.append([str(atc_df.index[i]), atc1, a1_pred6h])

    # atactic fake
    # filepath = settings.MEDIA_ROOT + '/products/'+ 'train_with_pred2' + '.csv'
    # df = pd.read_csv(filepath, parse_dates=["date"], index_col="date").tail(360)#df = pd.read_json('NashDomRyazan-29-03-2019.json', encoding='utf-8')
    # atc_result = []
    # atc_result.append(['date', 'true', 'prediction'])
    # for i in range(df.shape[0]):
    #     if df.iloc[i]['activity'] == 0: activity = 0
    #     else: activity = df.iloc[i]['activity']
    #     if df.iloc[i]['pred6h'] == 0: pred6h = 0
    #     else: pred6h = df.iloc[i]['pred6h']
    #     atc_result.append([str(df.index[i]), activity, pred6h])

    atc_result = []
    atc_result.append(['date', 'true', 'prediction'])
    atc_result.append(['2012-12-01', '10', '20'])


    import json
    response = HttpResponse(json.dumps({'product_values_count': '123', 'atc_prediction':atc_result}))
    return response

    # context = {'predictions': 'update','df': 'update','pred': 'update'}
    # return render(request, "index.html", context)    

def index(request):
    import pickle
    imgs_adress = settings.STATIC_ROOT + '\\hello\\hello_imgs\\'
    context = {'predictions': 'index','df': 'index','pred': 'index','imgs_adress':imgs_adress, 'values':[12,13,14,15,16,17]}
    filepath = settings.MEDIA_ROOT + '/products/'+ 'train_with_pred2' + '.csv'
    df = pd.read_csv(filepath, parse_dates=["date"], index_col="date") #df = pd.read_json('NashDomRyazan-29-03-2019.json', encoding='utf-8')
    true_values = []; predictions = []; dates = []
    for i in range(df.shape[0]):
        true_values.append(df.iloc[i]['activity'])
        predictions.append(df.iloc[i]['pred6h'])    
        dates.append(str(df.index[i]))
    result = (true_values, predictions, dates)
    context['df'] = result#str(df.head(1000))
    context['values'] = [df['f0'][-1],df['f1'][-1],df['f2'][-1],df['f3'][-1],df['f4'][-1],df['f5'][-1]]
    return render(request, "index_boot.html", context)

def atc_index(request):
    import pickle
    imgs_adress = settings.STATIC_ROOT + '\\hello\\hello_imgs\\'
    context = {'predictions': 'index','df': 'index','pred': 'index','imgs_adress':imgs_adress, 'values':[12,13,14,15,16,17]}
    filepath = settings.MEDIA_ROOT + '/products/'+ 'train_with_pred2' + '.csv'
    df = pd.read_csv(filepath, parse_dates=["date"], index_col="date") #df = pd.read_json('NashDomRyazan-29-03-2019.json', encoding='utf-8')
    true_values = []; predictions = []; dates = []
    for i in range(df.shape[0]):
        true_values.append(df.iloc[i]['activity'])
        predictions.append(df.iloc[i]['pred6h'])    
        dates.append(str(df.index[i]))
    result = (true_values, predictions, dates)
    context['df'] = result#str(df.head(1000))
    context['values'] = [df['f0'][-1],df['f1'][-1],df['f2'][-1],df['f3'][-1],df['f4'][-1],df['f5'][-1]]
    return render(request, "index_atactic.html", context)

def db(request): # pdb.set_trace();
    import pickle
    context = {'predictions': 'db','df': 'db','pred': 'db'}
    return render(request, "index.html", context)

sibur-activity-web/hello/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">





    <title>Sibur</title>
  </head>
  <body>


    <script src="{% static 'jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'loader.js' %}"></script>
{% comment %} 

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">

          {% url 'hello:index' as main_url %}
          

          {% if request.path == main_url %} <li class="nav-item active"> {% else %} <li class="nav-item "> {% endif %}
            <a class="nav-link" href="{% url 'hello:index' %}">Главная</span> <span class="sr-only">(current)</span></a>
          </li>

        </ul>




      </div>



    </nav>
{% endcomment %} 
    
    
    <!-- <div class="container-fluid mt-5"> -->
    <div class="container-fluid">
      {% block content %}{% endblock %}

    </div>

{% comment %} 
    <footer class="footer bg-dark">
      <div class="container">
        <span class="text-muted">© 2019</span>
        
      </div>
    </footer>
{% endcomment %} 
    
  </body>
</html>


<style>
  /* Sticky footer styles - align footer to bottom
  -------------------------------------------------- */
  html {
    position: relative;
    min-height: 100%;
  }
  body {
    /* Margin bottom by footer height */
    /*margin-bottom: 60px;*/
  }
  .footer {
    position: absolute;
    bottom: 0;
    width: 100%;
    /* Set the fixed height of the footer here */
    height: 60px;
    background-color: #f5f5f5;
  }
</style>

sibur-activity-web/hello/templates/db.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container">


<h2>Page View Report</h2>


<ul>

{% for greeting in greetings %}
    <li>{{ greeting.when }}</li>
{% endfor %}

</ul>

</div>

{% endblock %}

sibur-activity-web/hello/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %} 


{#{predictions}#}
</br></br>predictions={{predictions}}</br>

{% comment %} 
<div class="row">
  <!-- LEFT COL WITH PROMO -->
  <div class="col-4 col-sm-4 col-md-4 col-lg-4 card shadow-sm">
    {% for line in df.2 %} 
      <div>{{line}}</div>
    {% endfor %}
  </div>
  <div class="col-4 col-sm-4 col-md-4 col-lg-4 card shadow-sm">
    {% for line in df.0 %} 
      <div>{{line}}</div>
    {% endfor %}
  </div>
  <div class="col-4 col-sm-4 col-md-4 col-lg-4 card shadow-sm">
    {% for line in df.1 %} 
      <div>{{line}}</div>
    {% endfor %}
  </div>
            
</div>
{% endcomment %} 










{% comment %} 
  </br></br>df={{df}}</br>
{% endcomment %} 

</br></br>pred={{pred}}</br>




<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'Sales', 'Expenses'],
          ['2004',  1000,      400],
          ['2005',  1170,      460],
          ['2006',  660,       1120],
          ['2007',  1030,      540]
        ]);

        var options = {
          title: 'Company Performance',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="curve_chart" style="width: 900px; height: 500px"></div>
  </body>
</html>




<script type="text/javascript">
  var refreshIntervalId = 0;
  var current_value = 0
  refreshIntervalId = window.setInterval(function(){
    console.log("test")

    var text_for_prediction = 'text_for_prediction'//$('textarea#mytextarea').val();

    $.ajax({
        type: "post",
        dataType: "json",
        context:this,
        timeout: 10000, // sends error after 3 sec
        url: "{% url 'hello:update'%}",
        data: {'csrfmiddlewaretoken' : '{{csrf_token}}', 'next' : '{{request.build_absolute_uri}}', 'text_for_prediction' :text_for_prediction },
        // success: function(resp) { 
        //   console.log('success' + resp)
        //   var pred_cat = resp.prediction['category']
        //   var pred_theme = resp.prediction['theme']
        //   var pred_ex = resp.prediction['executor']
        //   var count = $("#results").children().length;
        //   $("#results").prepend('<div><br><div>'+count+'.</div><div>Категория: '+pred_cat+'</div>' + '<div>Тема: '+pred_theme+'</div>' + '<div>Исполнитель: '+pred_ex+'</div></div>');
        // },
        success: function(resp) { 

            var test_value = resp.prediction[0][0]
            console.log('prediction' + resp.prediction)
            // console.log('success2_' + resp.product_values_count)


            current_value = current_value + test_value + 100
            // console.log('success3_' + current_value)

            google.charts.load('current', {'packages':['corechart']});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
              // var data = google.visualization.arrayToDataTable([
              //   ['Year', 'Sales', 'Expenses'],
              //   ['2004',  current_value,      400],
              //   ['2005',  1170,      460],
              //   ['2006',  660,       1120],
              //   ['2007',  1030,      540]
              // ]);




              
              var data = google.visualization.arrayToDataTable(resp.prediction);

              var options = {
                title: 'Company Performance',
                curveType: 'function',
                legend: { position: 'bottom' }
              };

              var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

              chart.draw(data, options);
            }





            // $("#results").prepend(resp.prediction);
        },
        fail: function(){
            console.log('fail')
            // self.innerHTML = "В корзину";
            // $(this).removeClass('loading_basket ');$(this).addClass('btn-outline-success');$(this).addClass('to_basket');
        },
        error:function(x,e) {
            console.log('error')
            if (x.status==0) {
                console.log('You are offline!!\n Please Check Your Network.');
            } else if(x.status==404) {
                console.log('Requested URL not found.');
            } else if(x.status==500) {
                console.log('Internel Server Error.');
            } else if(e=='parsererror') {
                console.log('Error.\nParsing JSON Request failed.');
            } else if(e=='timeout'){
                console.log('Request Time out.');
            } else {
                console.log('Unknow Error.\n'+x.responseText);
            }
            // self.innerHTML = "В корзину";
            // $(this).removeClass('loading_basket ');$(this).addClass('btn-outline-success');$(this).addClass('to_basket');
        }
        
    });



  }, 1000);
    /* later */
  // clearInterval(refreshIntervalId);
</script>



{% endblock %} 

sibur-activity-web/hello/templates/index_bakup.html
{% extends "base.html" %}
{% load static %}
{% block content %} 


{#{predictions}#}
</br></br>predictions={{predictions}}</br>
</br></br>df={{df}}</br>
</br></br>pred={{pred}}</br>

<!-- <div id="basket_link">Корзина</div> -->


<!-- <div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <input class="to_basket_number" type="number" value="1" min="1" style="width: 4em;" product_value_code="123">
</div> -->
<div class="p-3"></div>
<div >
<h5>Загрузить csv на сайт:</h5>
<form action="{% url 'hello:uploadcsv'%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="files" class="btn">Изменить картинку:</label>
    <input type="file" id="some_id" name="avatar2" >
    <input type="submit" value="Сохранить">
    <input type="hidden" id="custId" name="product_id" value="{{product.id}}">
    <input type="hidden" id="custId2" name="next" value="{{request.build_absolute_uri}}">
    {#{form.captcha}#}
</form>
    

<br><br>
<h4 class="mb-3">Введите текст обращения и нажмите "Отправить":</h4><br>

<textarea class="col-12 form-control" id="mytextarea" rows="4" cols="50">
	Когда движешься по Солотчинскому шоссе, в сторону Солотчи, на указателе мозолит глаз и сбивает водителя ванадльный иероглиф. 
</textarea>
<br>
<div class="text-center"> <!-- col-md-7 -->
    <span class="to_basket btn btn-outline-success" id="to_basket" product_code="123" >Отправить</span>
</div>
<div id="results"></div>

<!-- BASKET -->
<script type="text/javascript">
    // $(function(){
        $('.to_basket').on('click',function(){
            // var product_code = this.getAttribute("product_code");
            // var input_number = $('[product_value_code=' + product_code + ']')[0];
            // var curr_basket_link = $('[basket_link_code=' + product_code + ']')[0];
            // var product_value = $('[product_value_code=' + product_code + ']')[0].value;
            // var product_value = input_number.value;
            var text_for_prediction = $('textarea#mytextarea').val();

            var self = this
            if (self.innerHTML == "Отправить")
            {
                // self.innerHTML = "Добавление...";
                // $(this).addClass('loading_basket');
                // $(this).removeClass('btn-outline-success');
                // $(this).removeClass('to_basket ');

                // console.log('adding to basket product ' + product_code)
                $.ajax({
                    type: "post",
                    dataType: "json",
                    context:this,
                    timeout: 10000, // sends error after 3 sec
                    url: "{% url 'hello:update'%}",
                    data: {'csrfmiddlewaretoken' : '{{csrf_token}}', 'next' : '{{request.build_absolute_uri}}', 'text_for_prediction' :text_for_prediction },
      //               success: function(resp) { 
      //                   console.log('success' + resp)
      //                   var pred_cat = resp.prediction['category']
      //                   var pred_theme = resp.prediction['theme']
      //                   var pred_ex = resp.prediction['executor']
						// var count = $("#results").children().length;
      //                   $("#results").prepend('<div><br><div>'+count+'.</div><div>Категория: '+pred_cat+'</div>' + '<div>Тема: '+pred_theme+'</div>' + '<div>Исполнитель: '+pred_ex+'</div></div>');
      //               },
                    success: function(resp) { 
                        console.log('success' + resp.prediction)
                        // $("#results").prepend(resp.prediction);
                    },
                    fail: function(){
                        console.log('fail')
                        // self.innerHTML = "В корзину";
                        // $(this).removeClass('loading_basket ');$(this).addClass('btn-outline-success');$(this).addClass('to_basket');
                    },
                    error:function(x,e) {
                        console.log('error')
                        if (x.status==0) {
                            console.log('You are offline!!\n Please Check Your Network.');
                        } else if(x.status==404) {
                            console.log('Requested URL not found.');
                        } else if(x.status==500) {
                            console.log('Internel Server Error.');
                        } else if(e=='parsererror') {
                            console.log('Error.\nParsing JSON Request failed.');
                        } else if(e=='timeout'){
                            console.log('Request Time out.');
                        } else {
                            console.log('Unknow Error.\n'+x.responseText);
                        }
                        // self.innerHTML = "В корзину";
                        // $(this).removeClass('loading_basket ');$(this).addClass('btn-outline-success');$(this).addClass('to_basket');
                    }
                    
                });
            }

        })
    // });
</script>






{% endblock %} 




<!-- ATACTIC UPDATE GRAPH EVERY SECOND -->
<script type="text/javascript">
  var refreshIntervalId = 0;
  var current_value = 0
  refreshIntervalId = window.setInterval(function(){
    console.log("-------------atactic refresh")
    var text_for_prediction = 'text_for_prediction'//$('textarea#mytextarea').val();
    $.ajax({
        type: "post",
        dataType: "json",
        context:this,
        timeout: 10000, // sends error after 3 sec
        url: "{% url 'hello:atc_update'%}",
        data: {'csrfmiddlewaretoken' : '{{csrf_token}}', 'next' : '{{request.build_absolute_uri}}', 'text_for_prediction' :text_for_prediction },
        success: function(resp) { 
            // var test_value = resp.prediction[0][0]
            console.log('atactic' + resp.atc_prediction)
            // console.log('success2_' + resp.product_values_count)
            // current_value = current_value + test_value + 100
            // console.log('success3_' + current_value)
            
            // google.charts.load('current', {'packages':['corechart']});
            // google.charts.setOnLoadCallback(drawChart);
            // function drawChart() {
            //   var data = google.visualization.arrayToDataTable(resp.atc_prediction);
            //   var options = {
            //     title: 'Атактика',
            //     curveType: 'function',
            //     legend: { position: 'bottom' }
            //   };
            //   var chart = new google.visualization.LineChart(document.getElementById('curve_chart2'));
            //   chart.draw(data, options);
            // }
        },
        fail: function(){
            console.log('atactic fail')
        },
        error:function(x,e) {
            console.log('atactic error')
        }
        
    });
  }, 4000);
    /* later */
  // clearInterval(refreshIntervalId);
</script>